###
GET http://localhost:8000/
###
GET http://localhost:8000/1
###
GET http://localhost:8000/users
###
GET http://localhost:8000/users/1
###
POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "fulano",
    "email": "email@emaisl.com",
    "hashed_password": "hash"
}
###
DELETE http://localhost:8000/users/1 HTTP/1.1
###
PUT http://localhost:8000/users/1

{
    "hashed_password": "1234"
}
###