name: Continuo Integracion

on:
  push:
    branches: ["master"]

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t api_cole_sel .

      - name: Run integration tests
        run: docker run api_cole_sel pytest .
